---
- hosts: all
  vars:
    username: vagrant
  tasks:
    - name: Install aptitude package
      apt:
        name: aptitude
        force_apt_get: yes
      become: true
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
        update_cache: yes
      become: true
    - name: Install necessary packages
      apt:
        pkg:
          - python3
          - python3-pip
          - python3-dev
          - git
          - libssl-dev
          - libffi-dev
          - build-essential
          - gcc-mipsel-linux-gnu
          - qemu-system
          - qemu-user-static
          - qemu-user
        state: latest
      become: true
    - name: Create a directory for git repos it does not exist
      ansible.builtin.file:
        path: /home/{{ username }}/repos
        state: directory
        mode: '0755'
    - name: Upgrade pip to latest
      pip:
        name: pip
        executable: pip3
        extra_args: --upgrade
    - name: Install unicorn, capstone, keystone
      pip:
        name:
          - unicorn
          - capstone
          - keystone
        executable: pip3
        state: latest
    - name: Install pwntools
      pip:
        name: pwntools
        executable: pip3
        state: latest
    - name: Clone pwndbg
      git:
         repo: https://github.com/pwndbg/pwndbg.git
         dest: /home/{{ username }}/repos/pwndbg
         clone: yes
         update: yes
    - name: Install pwndbg
      command: bash /home/{{ username }}/repos/pwndbg/setup.sh
      args:
        chdir: /home/{{ username }}/repos/pwndbg
